disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - type_name
  - identifier_name
  - force_cast
  - nesting

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last

included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage

reporter: "xcode"
